<?php
#
# ARCHIVO DE SALIDA PARA EL XML CON CAF
# 111111111 LO DEBE REEMPLAZAR POR EL RUT DE LA EMPRESA SIN GUION E INCLUIR EL DV
$FACTRONICA["CAFXML"]="caf/caf_111111111.xml";
#
# TIPO DE DTE A REOBTENER
$FACTRONICA["TIPODTE"]="33";
#
# CANTIDAD DE FOLIOS A TIMBRAR, POR DEFECTO 1000 PARA OBTENER EL MAXIMO DISPONIBLE
$FACTRONICA["FOLIOSTIMBRAR"]=1000;
#
# RUT DE LA EMPRESA
$FACTRONICA["RUTPYME"]="11111111";
#
# DIGITO VERIFICADOR DE RUT DE LA EMPRESA
$FACTRONICA["DVRUTPYME"]="1";
#
# RUT DEL CERTIFICADO
$FACTRONICA["RUTCERTIFICADO"]="22222222";
#
# DIGITO VERIFICADOR DEL RUT DEL CERTIFICADO
$FACTRONICA["DVRUTCERTIFICADO"]="2";
#
# MAYUSCULAS E IGUAL A COMO SALE EN EL SII
$FACTRONICA["NOMBRECERTIFICADO"]="ELBA CALAO ILABACA CAMPOS";
#
# RUTA DEL ARCHIVO PEM CON EL CERTIFICADO DIGITAL, SE REQUIERE TRANSFORMAR EL CERTIFICADO PFX A PEM
# 222222222 LO DEBE REEMPLAZAR POR EL RUT DEL CERTIFICADO SIN GUION E INCLUIR EL DV
$FACTRONICA["CERTIFICADOPEM"]='pem/certificado_222222222.pem'; 
#
# CLAVE DEL CERTIFICADO DIGITAL
$FACTRONICA["CERTIFICADOCLAVE"]='abc123';
#
# RANGO INICIAL DE CAF A OBTENER, NO MODIFICAR ESTE PARAMETRO
$FACTRONICA["FOLIOINICIAL"]=null;
#
# RANGO FINAL DE CAF A OBTENER, NO MODIFICAR ESTE PARAMETRO
$FACTRONICA["FOLIOFINAL"]=null;
#
# RANGO AUTORIZADO DE CAF A OBTENER, NO MODIFICAR ESTE PARAMETRO
$FACTRONICA["FOLIOSAUTORIZADOS"]=null;

?>
